FORD_CATEGORIES = [
    {
        "code": "1",
        "name": "Natural Sciences",
        "groups": [
            {
                "code": "1.1",
                "name": "Mathematics",
                "items": [
                    ("1.1.1", "Pure Mathematics"),
                    ("1.1.2", "Applied Mathematics"),
                    ("1.1.3", "Statistics and Probability"),
                    ("1.1.9", "Other mathematics"),
                ],
            },
            {
                "code": "1.2",
                "name": "Computer and Information Sciences",
                "items": [
                    ("1.2.1", "Computer sciences, information science, bioinformatics"),
                    ("1.2.2", "Scientific computing"),
                    ("1.2.3", "Information systems"),
                    ("1.2.4", "Databases, data mining, data curation, computational modelling"),
                    ("1.2.5", "Software engineering"),
                    ("1.2.9", "Other computer and information sciences"),
                ],
            },
            {
                "code": "1.3",
                "name": "Physical Sciences",
                "items": [
                    ("1.3.1", "Atomic, molecular and chemical physics"),
                    ("1.3.2", "Condensed Matter Physics"),
                    ("1.3.3", "Particles and field physics"),
                    ("1.3.4", "Nuclear Physics"),
                    ("1.3.5", "Fluids and plasma physics"),
                    ("1.3.6", "Optics"),
                    ("1.3.7", "Acoustics"),
                    ("1.3.8", "Astronomy"),
                    ("1.3.9", "Other physical sciences"),
                ],
            },
            {
                "code": "1.4",
                "name": "Chemical Sciences",
                "items": [
                    ("1.4.1", "Organic Chemistry"),
                    ("1.4.2", "Inorganic and nuclear chemistry"),
                    ("1.4.3", "Physical Chemistry"),
                    ("1.4.4", "Polymer science"),
                    ("1.4.5", "Electrochemistry"),
                    ("1.4.6", "Colloid chemistry"),
                    ("1.4.7", "Analytical chemistry"),
                    ("1.4.9", "Other chemical sciences"),
                ],
            },
            {
                "code": "1.5",
                "name": "Earth and Related Environmental Sciences",
                "items": [
                    ("1.5.1", "Geosciences, multidisciplinary"),
                    ("1.5.2", "Mineralogy"),
                    ("1.5.3", "Palaeontology"),
                    ("1.5.4", "Geochemistry and geophysics"),
                    ("1.5.5", "Physical geography"),
                    ("1.5.6", "Geology"),
                    ("1.5.7", "Volcanology"),
                    ("1.5.8", "Environmental sciences"),
                    ("1.5.9", "Meteorology and atmospheric sciences"),
                    ("1.5.10", "Climatic research"),
                    ("1.5.11", "Hydrology"),
                    ("1.5.12", "Oceanography, hydrology, water resources"),
                    ("1.5.13", "Other earth and related environmental sciences"),
                ],
            },
            {
                "code": "1.6",
                "name": "Biological Sciences",
                "items": [
                    ("1.6.1", "Cell biology, microbiology"),
                    ("1.6.2", "Virology"),
                    ("1.6.3", "Biochemistry and molecular biology"),
                    ("1.6.4", "Biochemical research methods"),
                    ("1.6.5", "Mycology"),
                    ("1.6.6", "Biophysics"),
                    ("1.6.7", "Genetics and heredity"),
                    ("1.6.8", "Reproductive biology"),
                    ("1.6.9", "Developmental biology"),
                    ("1.6.10", "Plant sciences, botany"),
                    ("1.6.11", "Zoology, ornithology, entomology, behavioural sciences biology"),
                    ("1.6.12", "Marine biology, freshwater biology, limnology"),
                    ("1.6.13", "Ecology"),
                    ("1.6.14", "Biodiversity conservation"),
                    ("1.6.15", "Biology"),
                    ("1.6.16", "Other biological sciences"),
                ],
            },
            {
                "code": "1.7",
                "name": "Other Natural Sciences",
                "items": [("1.7.1", "Other natural sciences")],
            },
        ],
    },
    {
        "code": "2",
        "name": "Engineering and Technology",
        "groups": [
            {
                "code": "2.1",
                "name": "Civil Engineering",
                "items": [
                    ("2.1.1", "Civil engineering"),
                    ("2.1.2", "Architecture engineering"),
                    ("2.1.3", "Construction engineering, Municipal and structural engineering"),
                    ("2.1.4", "Transport engineering"),
                    ("2.1.5", "Construction Management"),
                    ("2.1.9", "Other civil engineering"),
                ],
            },
            {
                "code": "2.2",
                "name": "Electrical Engineering, Electronic Engineering, Information Engineering",
                "items": [
                    ("2.2.1", "Electrical and electronic engineering"),
                    ("2.2.2", "Robotics and automatic control"),
                    ("2.2.3", "Automation and control systems"),
                    ("2.2.4", "Communication engineering and systems"),
                    ("2.2.5", "Telecommunications"),
                    ("2.2.9", "Other electrical engineering, electronic engineering, information engineering"),
                ],
            },
            {
                "code": "2.3",
                "name": "Mechanical Engineering",
                "items": [
                    ("2.3.1", "Mechanical engineering"),
                    ("2.3.2", "Applied mechanics"),
                    ("2.3.3", "Thermodynamics"),
                    ("2.3.4", "Aerospace engineering"),
                    ("2.3.5", "Nuclear related engineering"),
                    ("2.3.6", "Audio engineering, reliability analysis"),
                    ("2.3.9", "Other mechanical engineering"),
                ],
            },
            {
                "code": "2.4",
                "name": "Chemical Engineering",
                "items": [
                    ("2.4.1", "Chemical engineering"),
                    ("2.4.2", "Chemical process engineering"),
                    ("2.4.9", "Other chemical engineering"),
                ],
            },
            {
                "code": "2.5",
                "name": "Materials Engineering",
                "items": [
                    ("2.5.1", "Materials engineering"),
                    ("2.5.2", "Ceramics"),
                    ("2.5.3", "Composites"),
                    ("2.5.4", "Paper and wood"),
                    ("2.5.5", "Textiles"),
                    ("2.5.6", "Coating and films"),
                    ("2.5.9", "Other materials engineering"),
                ],
            },
            {
                "code": "2.6",
                "name": "Medical Engineering",
                "items": [
                    ("2.6.1", "Medical engineering"),
                    ("2.6.2", "Medical laboratory technology"),
                    ("2.6.9", "Other medical engineering"),
                ],
            },
            {
                "code": "2.7",
                "name": "Environmental Engineering",
                "items": [
                    ("2.7.1", "Environmental and geological engineering, geotechnics"),
                    ("2.7.2", "Petroleum engineering"),
                    ("2.7.3", "Mining and mineral processing"),
                    ("2.7.4", "Marine engineering, sea vessels"),
                    ("2.7.5", "Ocean engineering"),
                    ("2.7.6", "Energy and fuels"),
                    ("2.7.7", "Remote sensing"),
                    ("2.7.9", "Other environmental engineering"),
                ],
            },
            {
                "code": "2.8",
                "name": "Environmental Biotechnology",
                "items": [
                    ("2.8.1", "Environmental biotechnology"),
                    ("2.8.2", "Bioremediation, diagnostic biotechnologies"),
                    ("2.8.3", "Environmental biotechnology related ethics"),
                    ("2.8.9", "Other environmental biotechnology"),
                ],
            },
            {
                "code": "2.9",
                "name": "Industrial Biotechnology",
                "items": [
                    ("2.9.1", "Industrial biotechnology"),
                    ("2.9.2", "Bioprocessing technologies"),
                    ("2.9.3", "Bioproducts"),
                    ("2.9.9", "Other industrial biotechnology"),
                ],
            },
            {
                "code": "2.10",
                "name": "Nano-technology",
                "items": [
                    ("2.10.1", "Nano-materials"),
                    ("2.10.2", "Nano-processes"),
                    ("2.10.9", "Other nano-technology"),
                ],
            },
            {
                "code": "2.11",
                "name": "Other Engineering and Technologies",
                "items": [
                    ("2.11.1", "Food and beverages"),
                    ("2.11.2", "Mineral and mining engineering, mineral and metallurgical processing"),
                    ("2.11.3", "Textiles"),
                    ("2.11.9", "Other engineering and technologies"),
                ],
            },
        ],
    },
    {
        "code": "3",
        "name": "Medical and Health Sciences",
        "groups": [
            {
                "code": "3.1",
                "name": "Basic Medicine",
                "items": [
                    ("3.1.1", "Anatomy and morphology"),
                    ("3.1.2", "Human genetics"),
                    ("3.1.3", "Immunology"),
                    ("3.1.4", "Neurosciences"),
                    ("3.1.5", "Pharmacology and pharmacy"),
                    ("3.1.6", "Medicinal chemistry"),
                    ("3.1.7", "Toxicology"),
                    ("3.1.8", "Physiology"),
                    ("3.1.9", "Pathology"),
                    ("3.1.10", "Other basic medicine"),
                ],
            },
            {
                "code": "3.2",
                "name": "Clinical Medicine",
                "items": [
                    ("3.2.1", "Andrology"),
                    ("3.2.2", "Anaesthesiology"),
                    ("3.2.3", "Cardiology"),
                    ("3.2.4", "Endocrinology and metabolism"),
                    ("3.2.5", "Gastroenterology and hepatology"),
                    ("3.2.6", "General and internal medicine"),
                    ("3.2.7", "Geriatrics and gerontology"),
                    ("3.2.8", "Haematology"),
                    ("3.2.9", "Infectious diseases"),
                    ("3.2.10", "Intensive care medicine"),
                    ("3.2.11", "Nuclear medicine"),
                    ("3.2.12", "Obstetrics and gynaecology"),
                    ("3.2.13", "Oncology"),
                    ("3.2.14", "Ophthalmology"),
                    ("3.2.15", "Orthopaedics"),
                    ("3.2.16", "Otorhinolaryngology"),
                    ("3.2.17", "Paediatrics"),
                    ("3.2.18", "Pathology"),
                    ("3.2.19", "Psychiatry"),
                    ("3.2.20", "Radiology, nuclear medicine and medical imaging"),
                    ("3.2.21", "Respiratory medicine"),
                    ("3.2.22", "Rheumatology"),
                    ("3.2.23", "Surgery"),
                    ("3.2.24", "Urology and nephrology"),
                    ("3.2.25", "Tropical medicine"),
                    ("3.2.26", "General practice and family medicine"),
                    ("3.2.27", "Dermatology and venereal diseases"),
                    ("3.2.28", "Allergy"),
                    ("3.2.29", "Critical care medicine"),
                    ("3.2.30", "Other clinical medicine subjects"),
                ],
            },
            {
                "code": "3.3",
                "name": "Health Sciences",
                "items": [
                    ("3.3.1", "Dentistry, oral surgery and medicine"),
                    ("3.3.2", "Nursing"),
                    ("3.3.3", "Nutrition, Dietetics"),
                    ("3.3.4", "Public health, environmental and occupational health"),
                    ("3.3.5", "Tropical medicine"),
                    ("3.3.6", "Parasitology"),
                    ("3.3.7", "Pharmacy"),
                    ("3.3.8", "Toxicology"),
                    ("3.3.9", "Other health sciences"),
                ],
            },
            {
                "code": "3.4",
                "name": "Medical Biotechnology",
                "items": [
                    ("3.4.1", "Health-related biotechnology"),
                    ("3.4.2", "Technologies involving the manipulation of cells, tissues, organs or the whole organism"),
                    ("3.4.3", "Technologies involving identifying the functioning of DNA, proteins and enzymes"),
                    ("3.4.4", "Biomaterials"),
                    ("3.4.9", "Other medical biotechnology"),
                ],
            },
            {
                "code": "3.5",
                "name": "Other Medical Sciences",
                "items": [
                    ("3.5.1", "Forensic science"),
                    ("3.5.2", "Other medical sciences"),
                ],
            },
        ],
    },
    {
        "code": "4",
        "name": "Agricultural and Veterinary Sciences",
        "groups": [
            {
                "code": "4.1",
                "name": "Agriculture, Forestry, and Fisheries",
                "items": [
                    ("4.1.1", "Agriculture"),
                    ("4.1.2", "Forestry"),
                    ("4.1.3", "Fisheries"),
                    ("4.1.4", "Soil science"),
                    ("4.1.5", "Horticulture, viticulture"),
                    ("4.1.6", "Agronomy, plant breeding and plant protection"),
                    ("4.1.9", "Other agricultural sciences"),
                ],
            },
            {
                "code": "4.2",
                "name": "Animal and Dairy Science",
                "items": [
                    ("4.2.1", "Animal and dairy science"),
                    ("4.2.2", "Pets"),
                    ("4.2.9", "Other animal and dairy science"),
                ],
            },
            {
                "code": "4.3",
                "name": "Veterinary Science",
                "items": [("4.3.1", "Veterinary science")],
            },
            {
                "code": "4.4",
                "name": "Agricultural Biotechnology",
                "items": [
                    ("4.4.1", "Agricultural biotechnology and food biotechnology"),
                    ("4.4.2", "GM technology"),
                    ("4.4.9", "Other agricultural biotechnology"),
                ],
            },
            {
                "code": "4.5",
                "name": "Other Agricultural Sciences",
                "items": [("4.5.1", "Other agricultural sciences")],
            },
        ],
    },
    {
        "code": "5",
        "name": "Social Sciences",
        "groups": [
            {
                "code": "5.1",
                "name": "Psychology and Cognitive Sciences",
                "items": [
                    ("5.1.1", "Psychology"),
                    ("5.1.2", "Psychology, special"),
                    ("5.1.3", "Psychoanalysis"),
                    ("5.1.4", "Psychology, clinical"),
                    ("5.1.9", "Other psychology"),
                ],
            },
            {
                "code": "5.2",
                "name": "Economics and Business",
                "items": [
                    ("5.2.1", "Economics"),
                    ("5.2.2", "Econometrics"),
                    ("5.2.3", "Industrial relations"),
                    ("5.2.4", "Business and Management"),
                    ("5.2.5", "Accounting"),
                    ("5.2.6", "Finance"),
                    ("5.2.9", "Other economics and business"),
                ],
            },
            {
                "code": "5.3",
                "name": "Educational Sciences",
                "items": [
                    ("5.3.1", "Education, general"),
                    ("5.3.2", "Education, special"),
                    ("5.3.9", "Other educational sciences"),
                ],
            },
            {
                "code": "5.4",
                "name": "Sociology",
                "items": [
                    ("5.4.1", "Sociology"),
                    ("5.4.2", "Demography"),
                    ("5.4.3", "Anthropology, ethnology"),
                    ("5.4.4", "Social topics"),
                    ("5.4.9", "Other sociology"),
                ],
            },
            {
                "code": "5.5",
                "name": "Law",
                "items": [
                    ("5.5.1", "Law"),
                    ("5.5.2", "Criminology, penology"),
                    ("5.5.9", "Other law"),
                ],
            },
            {
                "code": "5.6",
                "name": "Political Science",
                "items": [
                    ("5.6.1", "Political science"),
                    ("5.6.2", "Public administration"),
                    ("5.6.3", "Organisation theory"),
                    ("5.6.9", "Other political science"),
                ],
            },
            {
                "code": "5.7",
                "name": "Social and Economic Geography",
                "items": [
                    ("5.7.1", "Human geography"),
                    ("5.7.2", "Environmental sciences"),
                    ("5.7.3", "Economic geography"),
                    ("5.7.4", "Urban studies"),
                    ("5.7.5", "Transport planning and social aspects of transport"),
                    ("5.7.9", "Other social and economic geography"),
                ],
            },
            {
                "code": "5.8",
                "name": "Media and Communications",
                "items": [
                    ("5.8.1", "Media studies"),
                    ("5.8.2", "Journalism"),
                    ("5.8.3", "Information science"),
                    ("5.8.4", "Library science"),
                    ("5.8.9", "Other media and communications"),
                ],
            },
            {
                "code": "5.9",
                "name": "Other Social Sciences",
                "items": [("5.9.1", "Other social sciences")],
            },
        ],
    },
    {
        "code": "6",
        "name": "Humanities and the Arts",
        "groups": [
            {
                "code": "6.1",
                "name": "History and Archaeology",
                "items": [
                    ("6.1.1", "History"),
                    ("6.1.2", "Archaeology"),
                    ("6.1.3", "Modern History"),
                    ("6.1.5", "African History"),
                    ("6.1.9", "Other history and archaeology"),
                ],
            },
            {
                "code": "6.2",
                "name": "Languages and Literature",
                "items": [
                    ("6.2.1", "General language studies"),
                    ("6.2.2", "Specific languages"),
                    ("6.2.3", "General literature studies"),
                    ("6.2.4", "Specific literatures"),
                    ("6.2.5", "Literary theory"),
                    ("6.2.6", "Comparative literature studies"),
                    ("6.2.9", "Other languages and literature"),
                ],
            },
            {
                "code": "6.3",
                "name": "Philosophy, Ethics and Religion",
                "items": [
                    ("6.3.1", "Philosophy, History and Philosophy of science and technology"),
                    ("6.3.2", "Ethics"),
                    ("6.3.3", "Theology"),
                    ("6.3.4", "Religious studies"),
                    ("6.3.9", "Other philosophy, ethics and religion"),
                ],
            },
            {
                "code": "6.4",
                "name": "Arts",
                "items": [
                    ("6.4.1", "Arts, Art history"),
                    ("6.4.2", "Performing arts studies"),
                    ("6.4.3", "Folklore studies"),
                    ("6.4.4", "Studies on Film, Radio and Television"),
                    ("6.4.9", "Other arts"),
                ],
            },
            {
                "code": "6.5",
                "name": "Other Humanities",
                "items": [("6.5.1", "Other humanities")],
            },
        ],
    },
]

KENYA_COUNTIES = [
    "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet", "Embu", "Garissa",
    "Homa Bay", "Isiolo", "Kajiado", "Kakamega", "Kericho", "Kiambu", "Kilifi",
    "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu",
    "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Mombasa",
    "Murang'a", "Nairobi", "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua",
    "Nyeri", "Samburu", "Siaya", "Taita-Taveta", "Tana River", "Tharaka-Nithi",
    "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot",
]

ETHNICITIES = [
    "Kikuyu", "Luhya", "Kalenjin", "Luo", "Kamba", "Somali", "Kisii", "Mijikenda",
    "Meru", "Maasai", "Borana", "Embu", "Gabra", "Giriama", "Ilchamus", "Kuria",
    "Nandi", "Ogiek", "Orma", "Pokomo", "Pokot", "Rendille", "Samburu", "Suba",
    "Swahili", "Taita", "Taveta", "Teso", "Tharaka", "Tugen", "Turkana", "Arab",
    "Asian/Indian", "El Molo", "European", "Nubi", "Other African", "Other",
    "Prefer not to say",
]

NATIONALITIES = [
    "Kenya", "Uganda", "Tanzania", "Rwanda", "Burundi", "South Sudan", "Ethiopia",
    "Somalia", "South Africa", "Nigeria", "Ghana", "United Kingdom", "USA",
    "Canada", "Germany", "France", "India", "China", "Australia", "Other",
]

QUALIFICATIONS = [
    "Master's Degree",
    "PhD",
    "Post-Doctoral",
    "Professor",
]
