# Generated by Django 6.1.1 on 2026-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_projectactivity_activitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
    ]
