# Generated by Django 5.2.1 on 2026-03-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "default_due_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days after project start when this activity is due.",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="grants.grant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
