# Generated by Django 6.1.1 on 2026-09-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grantactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-grant_date']},
        ),
        migrations.AddField(
            model_name='grant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='company',
            field=models.CharField(default='National Research Fund', max_length=200),
        ),
        migrations.AlterField(
            model_name='grant',
            name='contract',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Freelance', 'Freelancer'), ('Organization', 'Organization'), ('Individual', 'Individual')], default='Organization', max_length=150),
        ),
        migrations.AlterField(
            model_name='grant',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='grant',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kakamega', 'Kakamega'), ('Nyeri', 'Nyeri'), ('Remote', 'Remote'), ('Nationwide', 'Nationwide'), ('Kenya', 'Kenya'), ('East Africa', 'East Africa'), ('Africa', 'Africa'), ('International', 'International')], default='Nationwide', max_length=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='grant',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grant',
            name='vacancy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='GrantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grant_docs/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants.grant')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
