# Generated by Django 6.1.1 on 2026-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_grant_slug_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantactivity',
            name='requires_document',
            field=models.BooleanField(default=False, help_text='If enabled, the grantee must upload a document for this activity.'),
        ),
    ]
