# Generated by Django 5.2.1 on 2025-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("GRANT_MANAGER", "Grant Manager"),
                    ("REVIEWER", "Reviewer"),
                    ("APPLICANT", "Applicant"),
                ],
                default="APPLICANT",
                max_length=20,
            ),
        ),
    ]
