# Generated by Django 6.1.1 on 2026-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(max_length=80)),
                ('id_number', models.CharField(max_length=80)),
                ('id_document', models.FileField(blank=True, upload_to='reviewer_apps/ids/%Y/%m/')),
                ('is_pwd', models.BooleanField(default=False)),
                ('pwd_number', models.CharField(blank=True, max_length=80)),
                ('home_county', models.CharField(blank=True, max_length=80)),
                ('ethnicity', models.CharField(blank=True, max_length=80)),
                ('institution', models.CharField(max_length=255)),
                ('highest_qualification', models.CharField(max_length=80)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('cv', models.FileField(upload_to='reviewer_apps/cvs/%Y/%m/')),
                ('qualification_document', models.FileField(upload_to='reviewer_apps/qualifications/%Y/%m/')),
                ('area_of_expertise', models.TextField()),
                ('ford_categories', models.JSONField(blank=True, default=list)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('conduct_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
